### ISSUE TITLE
Trip einstellen wenn keine locations verfügbar

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/brainstorm#10]
UI und message die dem User angezeigt wird, wenn er einen Trip einstellen will, aber noch keine Locations hat. 

![screen shot 2015-06-17 at 3 48 42 pm](https://cloud.githubusercontent.com/assets/5221667/8209153/b613c7e4-150b-11e5-81dd-7d249da18c9e.png)

**Comment by SteffenGorenflo** [comment]
new design --> no longer needed
