### ISSUE TITLE
Default Location beim registrieren

### ISSUE THREAD

**Issue by T1m1** [locator-kn/brainstorm#13]
Wie wäre es, wenn wir dem User beim Registrieren eine default location (seine Stadt) erstellen? Dazu müsste er halt beim Registrieren seinen Wohnort mit angeben... 
Somit würden wir ihm die Vorzüge von Locations zeigen, ihn aber nicht zwingen selbst eine anlegen zu müssen.

Bsp.:
Locationname: Mein {Stadtname} 
Kategorie: Stadt
Beschreibung: Ich zeige euch die schönen und geheimen Plätzer von {Stadtname}.
Bild: GoogleMaps

**Comment by timoweiss** [comment]
und eine google map und die location zu taggen?

**Comment by T1m1** [comment]
Nope, jede Stadt hat doch sicher eine default googlemap position (wenn ich Konstanz eingebe ist es ja auch ein map punkt) den dann für das Bild verwenden

**Comment by timoweiss** [comment]
aha, naja nicht so cool, mit location ist dann für die tonne oder nicht?

**Comment by T1m1** [comment]
Nö gar nicht.. schon mal eine das man sieht wie sowas aussehen könnte.. finde das ist die Beste Idee die es jemals gab!
Diskutieren wir das Montag mit allen

**Comment by T1m1** [comment]
@locator-kn/owners -> soll implementiert werden.
- fancy location oder
- Heimatstadt mit angeben und daraus eine Location generieren

**Comment by SteffenGorenflo** [comment]
da jetzt locations public sind und jeder diese zum erstellen von trips verwenden kann, gibt es nur eine default location (Strandbar) welche in jedem Profil verlinkt ist und entsprechend markiert ist

**Comment by SteffenGorenflo** [comment]
done
