### ISSUE TITLE
Bild von Jo auf die Projektseite

### ISSUE THREAD

**Issue by loptik** [locator-kn/brainstorm#14]
Text:
Prof. Jo Wickert

Pendelt zwischen Berlin, Meersburg und Konstanz. 0

![1000](https://cloud.githubusercontent.com/assets/12908463/8615827/a9c597ea-26f6-11e5-8e6e-1bfa266fadeb.jpeg)

**Comment by SteffenGorenflo** [comment]
![lukas](https://cloud.githubusercontent.com/assets/5612074/8616587/eb269f26-26fc-11e5-9bbf-318bc55c7feb.jpg)

Bild bitte gerne in den gleichen ausmaßen

**Comment by SteffenGorenflo** [comment]
done
